const carData = {
  Mercedes: {
    A: ["A-Class", "AMG A35", "AMG A45"],
    B: ["B-Class"],
    C: ["C-Class", "CLA", "CLS", "CLE", "Citan", "AMG C43", "AMG C63"],
    E: ["E-Class", "AMG E53", "AMG E63"],
    S: ["S-Class", "SLC", "SL", "AMG S63", "AMG S65", "Maybach S-Class"],
    G: ["GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "AMG G63", "AMG GLE Coupe"],
    V: ["V-Class", "Vito", "Viano", "Vaneo"],
    X: ["X-Class"],
    Sprinter: ["Sprinter"],
    MarcoPolo: ["Marco Polo"],
    EQ: ["EQA", "EQB", "EQC", "EQE", "EQS", "EQV"],
  },
  BMW: {
    "1": ["1 Series", "M135i", "M140i"],
    "2": ["2 Series", "2 Series Gran Coupe", "2 Series Active Tourer", "M2"],
    "3": ["3 Series", "3 Series Touring", "3 Series Gran Turismo", "M3"],
    "4": ["4 Series", "4 Series Gran Coupe", "M4"],
    "5": ["5 Series", "5 Series Touring", "5 Series Gran Turismo", "M5"],
    "6": ["6 Series", "6 Series Gran Coupe", "6 Series Convertible", "M6"],
    "7": ["7 Series"],
    "8": ["8 Series", "M8"],
    X: ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "iX", "X3 M", "X5 M", "X6 M"],
    Z: ["Z3", "Z4", "Z8"],
    i: ["i3", "i4", "i7", "i8", "iX", "iX3"],
  },
  Audi: {
    A: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8"],
    Q: ["Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "SQ2", "SQ5", "SQ7", "SQ8"],
    S: ["S1", "S3", "S4", "S5", "S6", "S7", "S8"],
    RS: ["RS3", "RS4", "RS5", "RS6", "RS7", "RS Q3", "RS Q5", "RS Q8"],
    TT: ["TT", "TTS", "TT RS"],
    e: ["e-tron", "Q4 e-tron", "Q8 e-tron", "e-tron GT"],
    Allroad: ["A4 allroad", "A6 allroad"],
  },
  Volkswagen: {
    Golf: ["Golf", "Golf GTI", "Golf R", "Golf Sportsvan", "Golf Plus", "Golf Variant", "e-Golf"],
    Passat: ["Passat", "Passat CC", "Passat Alltrack", "Passat Variant"],
    Polo: ["Polo", "Polo GTI", "CrossPolo"],
    Tiguan: ["Tiguan", "Tiguan Allspace"],
    Touareg: ["Touareg"],
    T: ["T-Cross", "T-Roc", "Touran", "Transporter", "T6", "T5", "T4"],
    Arteon: ["Arteon", "Arteon Shooting Brake"],
    Up: ["up!", "e-up!"],
    ID: ["ID.3", "ID.4", "ID.5", "ID. Buzz", "ID.6"],
    Jetta: ["Jetta"],
    Sharan: ["Sharan"],
    Caddy: ["Caddy"],
    Amarok: ["Amarok"],
    Scirocco: ["Scirocco"],
    Beetle: ["Beetle", "New Beetle"],
    Fox: ["Fox"],
    Lupo: ["Lupo"],
    Passat: ["Passat", "Passat CC", "Passat Alltrack", "Passat Variant"],
  },
  Toyota: {
    Corolla: ["Corolla", "Corolla Touring Sports", "Corolla Hatchback", "Corolla Verso"],
    Camry: ["Camry"],
    Yaris: ["Yaris", "Yaris Cross", "GR Yaris"],
    RAV4: ["RAV4"],
    LandCruiser: ["Land Cruiser", "Land Cruiser Prado", "Land Cruiser V8"],
    Hilux: ["Hilux"],
    Prius: ["Prius", "Prius+ (Plus)", "Prius Plug-in"],
    C: ["C-HR"],
    Supra: ["Supra"],
    Aygo: ["Aygo", "Aygo X"],
    Avensis: ["Avensis", "Avensis Verso"],
    Auris: ["Auris"],
    Verso: ["Verso", "Verso-S"],
    Proace: ["Proace", "Proace City", "Proace Verso"],
    UrbanCruiser: ["Urban Cruiser"],
    Previa: ["Previa"],
    Celica: ["Celica"],
    MR2: ["MR2"],
    GT86: ["GT86"],
  },
  Ford: {
    Fiesta: ["Fiesta", "Fiesta ST"],
    Focus: ["Focus", "Focus ST", "Focus RS", "Focus C-MAX", "Focus Turnier"],
    Mondeo: ["Mondeo", "Mondeo Turnier"],
    Mustang: ["Mustang", "Mustang Mach-E"],
    Kuga: ["Kuga"],
    Puma: ["Puma"],
    EcoSport: ["EcoSport"],
    S: ["S-MAX"],
    Galaxy: ["Galaxy"],
    Ranger: ["Ranger", "Ranger Raptor"],
    Transit: ["Transit", "Transit Custom", "Transit Connect", "Transit Courier"],
    BMax: ["B-MAX"],
    CMax: ["C-MAX", "Grand C-MAX"],
    Edge: ["Edge"],
    Explorer: ["Explorer"],
    Tourneo: ["Tourneo Connect", "Tourneo Courier", "Tourneo Custom"],
    Maverick: ["Maverick"],
    Ka: ["Ka", "Ka+"],
    Fusion: ["Fusion"],
    Escort: ["Escort"],
    Sierra: ["Sierra"],
    Scorpio: ["Scorpio"],
    Probe: ["Probe"],
    Cougar: ["Cougar"],
  },
  Honda: {
    Civic: ["Civic", "Civic Type R"],
    Accord: ["Accord"],
    Jazz: ["Jazz"],
    CRV: ["CR-V"],
    HRV: ["HR-V"],
    NSX: ["NSX"],
    e: ["Honda e"],
  },
  Hyundai: {
    i: ["i10", "i20", "i30", "i40"],
    Kona: ["Kona", "Kona Electric"],
    Tucson: ["Tucson"],
    SantaFe: ["Santa Fe"],
    Bayon: ["Bayon"],
    Ioniq: ["Ioniq", "Ioniq 5", "Ioniq 6"],
  },
  Kia: {
    Picanto: ["Picanto"],
    Rio: ["Rio"],
    Ceed: ["Ceed", "ProCeed", "XCeed"],
    Sportage: ["Sportage"],
    Sorento: ["Sorento"],
    Niro: ["Niro", "e-Niro"],
    Stonic: ["Stonic"],
    EV6: ["EV6"],
  },
  Peugeot: {
    "108": ["108"],
    "208": ["208"],
    "308": ["308"],
    "508": ["508"],
    "2008": ["2008"],
    "3008": ["3008"],
    "5008": ["5008"],
    Rifter: ["Rifter"],
    Traveller: ["Traveller"],
  },
  Renault: {
    Clio: ["Clio"],
    Captur: ["Captur"],
    Megane: ["Megane", "Megane E-Tech"],
    Scenic: ["Scenic", "Grand Scenic"],
    Kadjar: ["Kadjar"],
    Koleos: ["Koleos"],
    Twingo: ["Twingo"],
    Zoe: ["Zoe"],
    Arkana: ["Arkana"],
  },
  Nissan: {
    Micra: ["Micra"],
    Juke: ["Juke"],
    Qashqai: ["Qashqai"],
    XTrail: ["X-Trail"],
    Leaf: ["Leaf"],
    Navara: ["Navara"],
    Note: ["Note"],
    Pulsar: ["Pulsar"],
    Almera: ["Almera"],
    Primera: ["Primera"],
    Maxima: ["Maxima"],
    Murano: ["Murano"],
    Pathfinder: ["Pathfinder"],
    Patrol: ["Patrol"],
    GT_R: ["GT-R"],
    "370Z": ["370Z"],
    "350Z": ["350Z"],
    Cube: ["Cube"],
    Tiida: ["Tiida"],
    Serena: ["Serena"],
    Terrano: ["Terrano"],
    Evalia: ["Evalia"],
  },
  Mazda: {
    Mazda2: ["Mazda2"],
    Mazda3: ["Mazda3", "Mazda3 Fastback"],
    Mazda6: ["Mazda6", "Mazda6 Wagon"],
    CX: ["CX-3", "CX-30", "CX-5", "CX-7", "CX-9"],
    MX: ["MX-5", "MX-5 RF"],
    RX: ["RX-8", "RX-7"],
    BT: ["BT-50"],
    Premacy: ["Premacy"],
    Tribute: ["Tribute"],
    Demio: ["Demio"],
  },
  Subaru: {
    Impreza: ["Impreza", "Impreza WRX", "Impreza WRX STI"],
    Legacy: ["Legacy", "Legacy Outback"],
    Outback: ["Outback"],
    Forester: ["Forester"],
    XV: ["XV", "Crosstrek"],
    BRZ: ["BRZ"],
    Levorg: ["Levorg"],
    Justy: ["Justy"],
    Tribeca: ["Tribeca"],
  },
  Lexus: {
    IS: ["IS", "IS F"],
    ES: ["ES"],
    GS: ["GS", "GS F"],
    LS: ["LS"],
    NX: ["NX"],
    RX: ["RX", "RX L"],
    UX: ["UX"],
    CT: ["CT"],
    LC: ["LC"],
    RC: ["RC", "RC F"],
    GX: ["GX"],
    LX: ["LX"],
    HS: ["HS"],
    LFA: ["LFA"],
  },
  Infiniti: {
    Q30: ["Q30"],
    Q50: ["Q50"],
    Q60: ["Q60"],
    Q70: ["Q70"],
    QX30: ["QX30"],
    QX50: ["QX50"],
    QX60: ["QX60"],
    QX70: ["QX70"],
    QX80: ["QX80"],
    EX: ["EX"],
    FX: ["FX"],
    M: ["M"],
    G: ["G"],
  },
  Acura: {
    ILX: ["ILX"],
    TLX: ["TLX"],
    RLX: ["RLX"],
    RDX: ["RDX"],
    MDX: ["MDX"],
    NSX: ["NSX"],
    ZDX: ["ZDX"],
    TSX: ["TSX"],
    RSX: ["RSX"],
  },
  Volvo: {
    S40: ["S40"],
    S60: ["S60", "S60 Cross Country"],
    S80: ["S80"],
    S90: ["S90"],
    V40: ["V40", "V40 Cross Country"],
    V50: ["V50"],
    V60: ["V60", "V60 Cross Country"],
    V70: ["V70"],
    V90: ["V90", "V90 Cross Country"],
    XC40: ["XC40"],
    XC60: ["XC60"],
    XC70: ["XC70"],
    XC90: ["XC90"],
    C30: ["C30"],
    C70: ["C70"],
    "850": ["850"],
    "940": ["940"],
    "960": ["960"],
  },
  Jaguar: {
    XE: ["XE"],
    XF: ["XF", "XFR", "XFR-S"],
    XJ: ["XJ", "XJR"],
    FType: ["F-Type"],
    EType: ["E-Type"],
    FPACE: ["F-PACE"],
    EPACE: ["E-PACE"],
    IPACE: ["I-PACE"],
    SType: ["S-Type"],
    XType: ["X-Type"],
  },
  LandRover: {
    Defender: ["Defender"],
    Discovery: ["Discovery", "Discovery Sport"],
    Freelander: ["Freelander"],
    RangeRover: ["Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  },
  Porsche: {
    911: ["911", "911 Carrera", "911 Turbo", "911 GT3", "911 GT2"],
    Boxster: ["Boxster", "718 Boxster"],
    Cayman: ["Cayman", "718 Cayman"],
    Panamera: ["Panamera"],
    Cayenne: ["Cayenne"],
    Macan: ["Macan"],
    Taycan: ["Taycan"],
    CarreraGT: ["Carrera GT"],
    918: ["918 Spyder"],
  },
  Tesla: {
    ModelS: ["Model S"],
    Model3: ["Model 3"],
    ModelX: ["Model X"],
    ModelY: ["Model Y"],
    Roadster: ["Roadster"],
    Cybertruck: ["Cybertruck"],
    Semi: ["Semi"],
  },
  Fiat: {
    500: ["500", "500C", "500L", "500X", "Abarth 500"],
    Panda: ["Panda"],
    Punto: ["Punto", "Grande Punto", "Punto Evo"],
    Tipo: ["Tipo"],
    Bravo: ["Bravo"],
    Doblo: ["Doblo"],
    Fiorino: ["Fiorino"],
    Qubo: ["Qubo"],
    Sedici: ["Sedici"],
    Freemont: ["Freemont"],
    Croma: ["Croma"],
    Stilo: ["Stilo"],
    Multipla: ["Multipla"],
    Scudo: ["Scudo"],
    Ulysse: ["Ulysse"],
    Ducato: ["Ducato"],
  },
  Opel: {
    Astra: ["Astra", "Astra Sports Tourer", "Astra GTC"],
    Corsa: ["Corsa"],
    Insignia: ["Insignia", "Insignia Sports Tourer"],
    Mokka: ["Mokka", "Mokka X"],
    Crossland: ["Crossland X"],
    Grandland: ["Grandland X"],
    Zafira: ["Zafira", "Zafira Tourer"],
    Meriva: ["Meriva"],
    Adam: ["Adam"],
    Karl: ["Karl"],
    Combo: ["Combo"],
    Vivaro: ["Vivaro"],
    Movano: ["Movano"],
    Antara: ["Antara"],
    Cascada: ["Cascada"],
    Ampera: ["Ampera"],
    Tigra: ["Tigra"],
    Agila: ["Agila"],
    Signum: ["Signum"],
    Omega: ["Omega"],
    Vectra: ["Vectra"],
    Senator: ["Senator"],
    Calibra: ["Calibra"],
    Frontera: ["Frontera"],
  },
  Skoda: {
    Fabia: ["Fabia", "Fabia Combi"],
    Octavia: ["Octavia", "Octavia Combi", "Octavia Scout"],
    Superb: ["Superb", "Superb Combi"],
    Rapid: ["Rapid", "Rapid Spaceback"],
    Scala: ["Scala"],
    Kamiq: ["Kamiq"],
    Karoq: ["Karoq"],
    Kodiaq: ["Kodiaq"],
    Yeti: ["Yeti"],
    Roomster: ["Roomster"],
    Citigo: ["Citigo"],
  },
  Seat: {
    Ibiza: ["Ibiza"],
    Leon: ["Leon", "Leon ST", "Leon X-Perience"],
    Toledo: ["Toledo"],
    Arona: ["Arona"],
    Ateca: ["Ateca"],
    Tarraco: ["Tarraco"],
    Alhambra: ["Alhambra"],
    Altea: ["Altea", "Altea XL"],
    Mii: ["Mii"],
    Exeo: ["Exeo"],
    Cordoba: ["Cordoba"],
    Inca: ["Inca"],
  },
  Mini: {
    Hatch: ["Hatch", "Cooper", "Cooper S", "John Cooper Works"],
    Clubman: ["Clubman"],
    Countryman: ["Countryman"],
    Paceman: ["Paceman"],
    Coupe: ["Coupe"],
    Roadster: ["Roadster"],
    Cabrio: ["Cabrio"],
  },
  Mitsubishi: {
    SpaceStar: ["Space Star"],
    Colt: ["Colt"],
    Lancer: ["Lancer", "Lancer Evolution"],
    Outlander: ["Outlander", "Outlander PHEV"],
    ASX: ["ASX"],
    EclipseCross: ["Eclipse Cross"],
    Pajero: ["Pajero", "Shogun"],
    PajeroSport: ["Pajero Sport"],
    Grandis: ["Grandis"],
    Carisma: ["Carisma"],
    Galant: ["Galant"],
    "3000GT": ["3000GT"],
    L200: ["L200"],
  },
  Suzuki: {
    Swift: ["Swift"],
    Ignis: ["Ignis"],
    Baleno: ["Baleno"],
    Vitara: ["Vitara"],
    S_Cross: ["S-Cross"],
    Jimny: ["Jimny"],
    SX4: ["SX4"],
    GrandVitara: ["Grand Vitara"],
    Alto: ["Alto"],
    Splash: ["Splash"],
    WagonR: ["Wagon R"],
    Liana: ["Liana"],
    Kizashi: ["Kizashi"],
    Carry: ["Carry"],
  },
  Jeep: {
    Renegade: ["Renegade"],
    Compass: ["Compass"],
    Cherokee: ["Cherokee"],
    GrandCherokee: ["Grand Cherokee"],
    Wrangler: ["Wrangler"],
    Gladiator: ["Gladiator"],
    Patriot: ["Patriot"],
    Commander: ["Commander"],
    Liberty: ["Liberty"],
  },
  Dodge: {
    Caliber: ["Caliber"],
    Avenger: ["Avenger"],
    Journey: ["Journey"],
    Nitro: ["Nitro"],
    Charger: ["Charger"],
    Challenger: ["Challenger"],
    Durango: ["Durango"],
    RAM: ["RAM 1500", "RAM 2500", "RAM 3500"],
    Viper: ["Viper"],
    Dakota: ["Dakota"],
    Caravan: ["Caravan", "Grand Caravan"],
    Neon: ["Neon"],
  },
  Chrysler: {
    300: ["300", "300C"],
    200: ["200"],
    PT: ["PT Cruiser"],
    Voyager: ["Voyager", "Grand Voyager"],
    Pacifica: ["Pacifica"],
    Sebring: ["Sebring"],
    Crossfire: ["Crossfire"],
    Aspen: ["Aspen"],
    Neon: ["Neon"],
    Stratus: ["Stratus"],
    Concorde: ["Concorde"],
    LHS: ["LHS"],
    TownCountry: ["Town & Country"],
  },
  AlfaRomeo: {
    Giulietta: ["Giulietta"],
    Giulia: ["Giulia"],
    Stelvio: ["Stelvio"],
    Mito: ["MiTo"],
    "159": ["159"],
    "156": ["156"],
    "147": ["147"],
    "166": ["166"],
    "145": ["145"],
    "146": ["146"],
    Brera: ["Brera"],
    Spider: ["Spider"],
    GTV: ["GTV"],
    GT: ["GT"],
    "4C": ["4C"],
    "8C": ["8C Competizione"],
    Crosswagon: ["Crosswagon"],
  },
  Citroen: {
    C1: ["C1"],
    C2: ["C2"],
    C3: ["C3", "C3 Aircross", "C3 Picasso"],
    C4: ["C4", "C4 Cactus", "C4 Picasso", "C4 SpaceTourer", "C4 Aircross"],
    C5: ["C5", "C5 Aircross", "C5 Tourer"],
    C6: ["C6"],
    C8: ["C8"],
    Berlingo: ["Berlingo", "Berlingo Multispace"],
    Jumper: ["Jumper"],
    Jumpy: ["Jumpy"],
    Nemo: ["Nemo"],
    DS3: ["DS3"],
    DS4: ["DS4"],
    DS5: ["DS5"],
    Saxo: ["Saxo"],
    Xsara: ["Xsara", "Xsara Picasso"],
    ZX: ["ZX"],
    BX: ["BX"],
    AX: ["AX"],
    Visa: ["Visa"],
    C15: ["C15"],
  },
  DS: {
    DS3: ["DS3"],
    DS4: ["DS4"],
    DS5: ["DS5"],
    DS7: ["DS7 Crossback"],
    DS9: ["DS9"],
  },
  Smart: {
    Fortwo: ["Fortwo", "Fortwo Cabrio"],
    Forfour: ["Forfour"],
    Roadster: ["Roadster"],
    Crossblade: ["Crossblade"],
  },
  Saab: {
    "9_3": ["9-3"],
    "9_5": ["9-5"],
    "9_7X": ["9-7X"],
    "900": ["900"],
    "9000": ["9000"],
    "9_4X": ["9-4X"],
  },
  Lancia: {
    Ypsilon: ["Ypsilon"],
    Delta: ["Delta"],
    Musa: ["Musa"],
    Thema: ["Thema"],
    Voyager: ["Voyager"],
    Phedra: ["Phedra"],
    Lybra: ["Lybra"],
    Thesis: ["Thesis"],
    Zeta: ["Zeta"],
    Dedra: ["Dedra"],
    Kappa: ["Kappa"],
    Beta: ["Beta"],
    Gamma: ["Gamma"],
    Prisma: ["Prisma"],
    Flavia: ["Flavia"],
    Fulvia: ["Fulvia"],
    Stratos: ["Stratos"],
    Montecarlo: ["Montecarlo"],
  },
  Daihatsu: {
    Cuore: ["Cuore"],
    Sirion: ["Sirion"],
    Terios: ["Terios"],
    Materia: ["Materia"],
    Copen: ["Copen"],
    Charade: ["Charade"],
    Move: ["Move"],
    Trevis: ["Trevis"],
    YRV: ["YRV"],
    Applause: ["Applause"],
    Feroza: ["Feroza"],
    Rocky: ["Rocky"],
  },
  Rover: {
    "25": ["25"],
    "45": ["45"],
    "75": ["75"],
    "100": ["100"],
    "200": ["200"],
    "400": ["400"],
    "600": ["600"],
    "800": ["800"],
    Streetwise: ["Streetwise"],
    CityRover: ["CityRover"],
    Metro: ["Metro"],
    Maestro: ["Maestro"],
    Montego: ["Montego"],
    Mini: ["Mini"],
  },
  Dacia: {
    Logan: ["Logan", "Logan MCV"],
    Sandero: ["Sandero", "Sandero Stepway"],
    Duster: ["Duster"],
    Lodgy: ["Lodgy"],
    Dokker: ["Dokker"],
    Spring: ["Spring"],
  },
};

export default carData; 